### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by kenmazaika** [joreilly25/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by joreilly25** [comment]
Added mobile meta tag, unsure if possibly a more _Ruby way_ of doing it though, or if even necessary for this application.

**Comment by kenmazaika** [comment]
:+1:  Looks perfect!
